"""add_parent_attempt_id_to_problem_attempts

Revision ID: 9ce3f900bd5a
Revises: d9e7095a0c31
Create Date: 2026-09-23 20:54:11.504001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ce3f900bd5a'
down_revision: Union[str, Sequence[str], None] = 'd9e7095a0c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem_attempts', sa.Column('parent_attempt_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_problem_attempts_parent_attempt_id'), 'problem_attempts', ['parent_attempt_id'], unique=False)
    op.create_foreign_key('fk_problem_attempts_parent_attempt_id', 'problem_attempts', 'problem_attempts', ['parent_attempt_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_problem_attempts_parent_attempt_id', 'problem_attempts', type_='foreignkey')
    op.drop_index(op.f('ix_problem_attempts_parent_attempt_id'), table_name='problem_attempts')
    op.drop_column('problem_attempts', 'parent_attempt_id')
    # ### end Alembic commands ###

