"""add_embedding_column_to_problems

Revision ID: f2cd3c36eea4
Revises: cda42da60858
Create Date: 2026-09-23 18:34:37.959352

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2cd3c36eea4'
down_revision: Union[str, Sequence[str], None] = 'cda42da60858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'embedding')
    # ### end Alembic commands ###
