"""make_feedback_rating_nullable

Revision ID: ff4b099528df
Revises: 9ce3f900bd5a
Create Date: 2026-09-23 21:25:21.965121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff4b099528df'
down_revision: Union[str, Sequence[str], None] = '9ce3f900bd5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedbacks', 'rating',
               existing_type=sa.SMALLINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedbacks', 'rating',
               existing_type=sa.SMALLINT(),
               nullable=False)
    # ### end Alembic commands ###
